{{ if .Values.catalog.mysql }}
---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ProxySQLVersion
metadata:
  name: "2.0.4"
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  version: "2.0.4"
  proxysql:
    image: "{{ .Values.dockerRegistry }}"/proxysql:2.0.4
  exporter:
    image: "{{ .Values.dockerRegistry }}"/mysqld-exporter:v0.11.0
  podSecurityPolicies:
    databasePolicyName: percona-xtradb-db

 {{ end }}
